apiVersion: v1
kind: Service
metadata:
  name: cloudea-actuator
  labels:
    app: cloudea-actuator
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32080
      name: actuator
  selector:
    app: cloudea-actuator
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cloudea-actuator
spec:
  selector:
    matchLabels:
      app: cloudea-actuator # has to match .spec.template.metadata.labels
  serviceName: "cloudea-actuator"
  template:
    metadata:
      labels:
        app: cloudea-actuator # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: cloudea-actuator
          image: cloudea-actuator:0.1
          ports:
            - containerPort: 8080